# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-14 21:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_challenge', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Challenge',
            new_name='Item',
        ),
    ]
