# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-14 22:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_challenge', '0002_auto_20190514_2154'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Item',
            new_name='Challenges',
        ),
    ]
