# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-17 19:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_challenge', '0003_auto_20190514_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenges',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
